### ISSUE TITLE
Error when i tried to download image

### ISSUE THREAD

**Issue by xiaoniujz** [P2Oileen/CoNR_Dataset#1]
Hi, first of all, thank you for providing the dataset. When I composed the URL of the image, I found that if the image name contains a semicolon ';', the download will fail.

Here is my code:
```python
import os,sys
import numpy as np
import cv2
import wget
   
input_dir = "../CoNR_Dataset_annotation_only/annotation"
output_dir = "../CoNR_Dataset_Image_only/image"
ann_file_lists = os.listdir(input_dir)
prefix = "https://cdn.donmai.us/original/"

for name in ann_file_lists:
    image_name = name.split('.')[0] + "." + name.split('.')[1]

    first = image_name[:2]
    second = image_name[2:4]
    image_url = prefix + first + "/" + second + "/" + image_name
    output_path = output_dir + "/" + image_name

    wget.download(image_url,out=output_path)
```

For Example:
image_name = a09c7da0ee69f15825f88ec26c928eb0;00000115.jpg
image_url = https://cdn.donmai.us/original/a0/9c/a09c7da0ee69f15825f88ec26c928eb0;00000115.jpg
output_path = ../CoNR_Dataset_Image_only/image/a09c7da0ee69f15825f88ec26c928eb0;00000115.jpg

Error information:
```
urllib.error.HTTPError: HTTP Error 404: Not Found
```
![image](https://user-images.githubusercontent.com/33999434/233069918-b9b024e0-66d3-4820-97bf-183988cfaebe.png)

**Comment by P2Oileen** [comment]
This may be because the original authors of these pictures deleted their images on bandooru, or set some permission management. You can use `try` command to skip the images that cannot be downloaded 😢

**Comment by P2Oileen** [comment]
This problem probably has nothing to do with the `;`, maybe the original authors of these pictures deleted their pictures on bandooru website, or set certain permission management. You can use the `try` command to try to skip the pictures that cannot be downloaded. 
```python
try:
    wget.download(image_url, out=output_path)
except:
    continue
```
If you have other questions, please feel free to raise an issue 😊
